import type { ModelInfo } from '../types'

// Model IDs verified via GET /inference/v1/models against this account on 2026-08-04.
// Pricing is estimated — verify at fireworks.ai/pricing before presenting to customers.
export const MODELS: ModelInfo[] = [
  // ── Fireworks models (verified available on this account) ────────
  {
    id: 'accounts/fireworks/models/kimi-k3',
    name: 'Kimi K3',
    provider: 'fireworks',
    contextWindow: 131072,
    inputPricePerMillion: 2.0,
    outputPricePerMillion: 6.0,
    bestFor: 'frontier chat, reasoning, and complex Q&A',
    tags: ['chat', 'reasoning', 'code', 'long-context'],
    qualityTier: 5,
    latencyTier: 'mid',
    openWeights: true,
  },
  {
    id: 'accounts/fireworks/models/deepseek-v4-pro',
    name: 'DeepSeek V4 Pro',
    provider: 'fireworks',
    contextWindow: 131072,
    inputPricePerMillion: 3.0,
    outputPricePerMillion: 8.0,
    bestFor: 'reasoning-heavy and code-intensive tasks',
    tags: ['reasoning', 'code', 'function-calling'],
    qualityTier: 5,
    latencyTier: 'mid',
    openWeights: true,
  },
  {
    id: 'accounts/fireworks/models/deepseek-v4-flash',
    name: 'DeepSeek V4 Flash',
    provider: 'fireworks',
    contextWindow: 131072,
    inputPricePerMillion: 0.5,
    outputPricePerMillion: 1.0,
    bestFor: 'high-volume, low-latency, cost-sensitive workloads',
    tags: ['chat', 'summarization', 'function-calling'],
    qualityTier: 3,
    latencyTier: 'low',
    openWeights: true,
  },
  {
    id: 'accounts/fireworks/models/kimi-k2p6',
    name: 'Kimi K2.6',
    provider: 'fireworks',
    contextWindow: 131072,
    inputPricePerMillion: 1.0,
    outputPricePerMillion: 3.0,
    bestFor: 'balanced quality and cost for chat and reasoning',
    tags: ['chat', 'reasoning', 'multilingual'],
    qualityTier: 4,
    latencyTier: 'mid',
    openWeights: true,
  },
  {
    id: 'accounts/fireworks/models/kimi-k2p7-code',
    name: 'Kimi K2.7 Code',
    provider: 'fireworks',
    contextWindow: 131072,
    inputPricePerMillion: 1.5,
    outputPricePerMillion: 4.0,
    bestFor: 'code generation, completion, and review',
    tags: ['code', 'function-calling'],
    qualityTier: 5,
    latencyTier: 'mid',
    openWeights: true,
  },
  {
    id: 'accounts/fireworks/models/gpt-oss-120b',
    name: 'GPT OSS 120B',
    provider: 'fireworks',
    contextWindow: 131072,
    inputPricePerMillion: 3.0,
    outputPricePerMillion: 8.0,
    bestFor: 'frontier open-source quality for reasoning and chat',
    tags: ['chat', 'reasoning', 'code'],
    qualityTier: 5,
    latencyTier: 'high',
    openWeights: true,
  },
  {
    id: 'accounts/fireworks/models/gpt-oss-20b',
    name: 'GPT OSS 20B',
    provider: 'fireworks',
    contextWindow: 131072,
    inputPricePerMillion: 0.9,
    outputPricePerMillion: 2.0,
    bestFor: 'fast, cost-effective open-source inference',
    tags: ['chat', 'summarization'],
    qualityTier: 3,
    latencyTier: 'low',
    openWeights: true,
  },
  {
    id: 'accounts/fireworks/models/minimax-m3',
    name: 'MiniMax M3',
    provider: 'fireworks',
    contextWindow: 524288,
    inputPricePerMillion: 0.5,
    outputPricePerMillion: 1.5,
    bestFor: '512k context window, long-document analysis',
    tags: ['long-context', 'summarization', 'multilingual'],
    qualityTier: 4,
    latencyTier: 'mid',
    openWeights: true,
  },
  {
    id: 'accounts/fireworks/models/minimax-m2p7',
    name: 'MiniMax M2.7',
    provider: 'fireworks',
    contextWindow: 1000000,
    inputPricePerMillion: 0.4,
    outputPricePerMillion: 0.4,
    bestFor: '1M token context window, lowest cost per token',
    tags: ['long-context', 'summarization'],
    qualityTier: 3,
    latencyTier: 'mid',
    openWeights: true,
  },
  {
    id: 'accounts/fireworks/models/qwen3p7-plus',
    name: 'Qwen 3.7+',
    provider: 'fireworks',
    contextWindow: 131072,
    inputPricePerMillion: 0.9,
    outputPricePerMillion: 2.7,
    bestFor: 'multilingual tasks, structured output',
    tags: ['multilingual', 'chat', 'summarization', 'function-calling'],
    qualityTier: 4,
    latencyTier: 'mid',
    openWeights: true,
  },
  {
    id: 'accounts/fireworks/models/glm-5p2',
    name: 'GLM 5.2',
    provider: 'fireworks',
    contextWindow: 131072,
    inputPricePerMillion: 1.0,
    outputPricePerMillion: 2.0,
    bestFor: 'Chinese and multilingual workloads',
    tags: ['multilingual', 'chat', 'reasoning'],
    qualityTier: 4,
    latencyTier: 'mid',
    openWeights: true,
  },
  {
    id: 'accounts/fireworks/models/nemotron-3-ultra-nvfp4',
    name: 'Nemotron 3 Ultra',
    provider: 'fireworks',
    contextWindow: 131072,
    inputPricePerMillion: 1.5,
    outputPricePerMillion: 4.0,
    bestFor: 'enterprise-grade reasoning with NVIDIA optimization',
    tags: ['reasoning', 'chat', 'code'],
    qualityTier: 4,
    latencyTier: 'mid',
    openWeights: true,
  },
  // ── Comparison anchors (closed-source) ──────────────────────────
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    contextWindow: 128000,
    inputPricePerMillion: 2.5,
    outputPricePerMillion: 10.0,
    bestFor: 'closed-API benchmark for quality',
    tags: ['chat', 'reasoning', 'code', 'function-calling', 'multilingual'],
    qualityTier: 5,
    latencyTier: 'mid',
    openWeights: false,
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o mini',
    provider: 'openai',
    contextWindow: 128000,
    inputPricePerMillion: 0.15,
    outputPricePerMillion: 0.6,
    bestFor: 'cheap closed-API alternative',
    tags: ['chat', 'summarization'],
    qualityTier: 3,
    latencyTier: 'low',
    openWeights: false,
  },
  {
    id: 'claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6',
    provider: 'anthropic',
    contextWindow: 200000,
    inputPricePerMillion: 3.0,
    outputPricePerMillion: 15.0,
    bestFor: 'long-context reasoning benchmark',
    tags: ['chat', 'reasoning', 'code', 'long-context', 'summarization'],
    qualityTier: 5,
    latencyTier: 'mid',
    openWeights: false,
  },
  {
    id: 'claude-haiku-4-5',
    name: 'Claude Haiku 4.5',
    provider: 'anthropic',
    contextWindow: 200000,
    inputPricePerMillion: 0.8,
    outputPricePerMillion: 4.0,
    bestFor: 'cheap closed-API with long context',
    tags: ['chat', 'summarization'],
    qualityTier: 3,
    latencyTier: 'low',
    openWeights: false,
  },
  {
    id: 'claude-opus-4-7',
    name: 'Claude Opus 4.7',
    provider: 'anthropic',
    contextWindow: 200000,
    inputPricePerMillion: 15.0,
    outputPricePerMillion: 75.0,
    bestFor: 'frontier-quality benchmark (expensive)',
    tags: ['reasoning', 'code', 'long-context'],
    qualityTier: 5,
    latencyTier: 'high',
    openWeights: false,
  },
]

export const FIREWORKS_MODELS = MODELS.filter((m) => m.provider === 'fireworks')
export const COMPARISON_MODELS = MODELS.filter((m) => m.provider !== 'fireworks')

export const DEFAULT_MODEL_ID = 'accounts/fireworks/models/kimi-k3'

export function findModel(id: string): ModelInfo | undefined {
  return MODELS.find((m) => m.id === id)
}

export function estimateCost(
  modelId: string,
  inputTokens: number,
  outputTokens: number,
): number {
  const m = findModel(modelId)
  if (!m) return 0
  return (
    (inputTokens / 1_000_000) * m.inputPricePerMillion +
    (outputTokens / 1_000_000) * m.outputPricePerMillion
  )
}
